name: Test on Push

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: "10.0.0"
      - run: pnpm install
      - run: pnpm test
        env:
          PORT: 4000
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
      